version: "3.5"
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: fetch-steam-data-new/server:latest
    ports:
      - "9020:9020"
